version: '3.8'
services:

  product-service:
    image: 561375666658.dkr.ecr.us-east-1.amazonaws.com/rish-spring-shop-product-service:0.0.1-SNAPSHOT
    container_name: product_service
    environment:
      - spring.profiles.active=dev
      - rss.postgres.host=db:5432
    ports:
      - '8080:80'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: 0.50
          memory: 512M
        reservations:
          cpus: 0.25
          memory: 128M

  db:
    image: postgres:14.1-alpine
    container_name: rish889_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local


